name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Tests"

    steps:
      - uses: actions/checkout@v3

      - name: Run Unit Tests
        run: ./gradlew test
