name: Publish

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          ./gradlew build
      - name: Sign & Publish
        env:
          SONATYPE_USERNAME: '${{ secrets.SONATYPE_USERNAME }}'
          SONATYPE_PASSWORD: '${{ secrets.SONATYPE_PASSWORD }}'
          ORG_GRADLE_PROJECT_signingKeyId: '${{ secrets.GPG_SIGNING_KEY_ID }}'
          ORG_GRADLE_PROJECT_signingKey: '${{ secrets.GPG_SIGNING_KEY }}'
          ORG_GRADLE_PROJECT_signingPassword: '${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}'
        run: |
          ./gradlew publish
