name: Publishing of release and snapshot versions

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: ./gradlew build
      - name: Sign & Publish
        if: github.ref == 'refs/heads/main'
        run: .ci/deploy.sh
        env:
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release
            -
          draft: true
          prerelease: false
